### ISSUE TITLE
Error for download links

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [ccmbioinfo/MetaFusion#2]
Hi @mapostolides ,

Would you please post full links for downloading the Singularity image and reference files?

The link for Singularity image gives an error 404 with `wget`, so I had to download it manually and then transfer to HPC. However, the same issue is with reference files, but they are huge and difficult to transfer.

Also, `RUN_MetaFusion.Singularity.sh` considers sim45_sim52 test data, but I am unclear on where to give input dir for my data? 

Thanks.

**Comment by mapostolides** [comment]
Hi Gurpreet,

Thanks for your interest in MetaFusion! 

1) Setting top-level directory

The variable `topdir=/hpf/largeprojects/ccmbio/mapostolides` specifies the path where you have downloaded the source code for MetaFusion. This is the top-level directory where the "MetaFusion" directory is inside, which you will need to set.

Then, within the MetaFusion directory, your outputs will be generated inside "RUNS". 

You can also set `runs_dir=$topdir/MetaFusion/RUNS` to be any path you want, and the outputs will be generated in that place

2) Getting links for wget command:

You are indeed correct that the links provided in the wiki will not work with wget. However, if you go to that link in your web browser, you can "right click" --> "Copy link address" on the "MetaFusion.simg" hypertext to get the following link, which will work with wget.

https://ndownloader.figshare.com/files/24741575

This will generate a file called "24741575", which will be 949M in size. You will then need to rename it to "MetaFusion.simg"

You can also do the same for the reference files and get the following link from the "right click"  --> "Copy link address"

https://ndownloader.figshare.com/articles/12855080/versions/1

Please let me know if this process works for you, and let me know if you have any other questions!

Best wishes,
Michael

**Comment by mapostolides** [comment]
Also, for the structure of the MetaFusion command, you may find our wiki helpful:

https://github.com/ccmbioinfo/MetaFusion/wiki/metafusion_sop

The input format of data for MetaFusion is in CFF format.

Best,
Michael

**Comment by gurpreet-bioinfo** [comment]
Thank you Michael @mapostolides !

1) (i) I meant about the path for a number of paired-end fastq files.

   (ii) I am still unclear regarding the following (inside `RUN_MetaFusion.Singularity.sh`):
    ```
    SIM45.SIM52.combined
    if [ $sim45_sim52 -eq 1 ]; 
    ```
   
   (iii) As I already have STAR alignment output from https://github.com/nf-core/rnaseq . Is there any provision to use that in 
    MetaFusion or I can only use fastq files? Are you planning any other way for integration with other inputs/pipelines?

   (iv) If I want to use GRCh38 version, apart from `.fasta` and `.fai` files under `reference_files`, what other changes am I suppose to make?

2) Ok, I did that earlier ("Copy link address"), but did not rename. Thanks for the hint. :-)

3) I successfully ran the test run (output files below under `SIM45.SIM52.benchmark.May-09-2021-SingularityV3`). However, I am wondering if there is a way to visualize the ouput ?
![image](https://user-images.githubusercontent.com/35698247/117360186-17013700-ae7e-11eb-9a3b-891021907d06.png)

Thanks.

**Comment by mapostolides** [comment]
Hi @gurpreet-bioinfo,

Great! It looks like you got the tool running correctly on one of the test datasets!

1. 
(i) MetaFusion does not take in FASTQ files, since it is not a fusion caller but rather a meta-caller. It might be helpful to take a look at our paper recently published in Bioinformatics to understand the workflow a bit better.

  (ii) That code basically checks to see whether you are running the "sim45_sim52" dataset. The script should have `sim45_sim52=1` set further up. It is just checking to see  that you have "turned on" that dataset.

(iii) As per (i), this tool does not take BAM or FASTQ as input, but rather CFF files. You will have to install and run fusion callers on your data to get the fusion calls, then convert those calls to CFF format.  Please refer to the wiki to learn more about this :)

(iv) MetaFusion will only work with with GRCh37, although it may be possible to offer GRCh38 at some point.

2) Great!

3) We do not have a way to  visualize the output integrated into our tool. However, there are other tools out there which do this

Question: I noticed you are using callerfilter7. The flag was set as follows:
`--num_tools=2`
Did you change it to `--num_tools=7` ?

**Comment by gurpreet-bioinfo** [comment]
Hi @mapostolides ,

Yes, I did go through the paper and had questions, which I posted earlier. Thank you for the clarification. :-)

Just a suggestion: The wiki documentation needs a bit of reorganization (many things are not at one place and one has to go back-and-forth). 

Would you please point towards visualization tool you think is one of the best for this output? (off course, I can/will Google it, but you are an expert in the area so would appreciate your recommendation).

Yes, I used 7 just to see what happens in output. 

Thank you again.

**Comment by mapostolides** [comment]
Hi @gurpreet-bioinfo ,

Thanks for the feedback. Which components of the wiki would you recommend putting in one place? 

For visualization, I've mostly used IGV by loading the BAM files from fusion callers and then viewing in split screen to visualize the reads. Also, without loading BAMs if I just input the breakpoints from metafusion.

If you're looking for a tool to visualize all of the output at once, on a per-fusion basis, I have not done this before so not sure which tool would be best for this.
